#!/usr/bin/bash

if [ -z "$PYFILE" ]; then
	echo "Error: Please set the PYFILE environment variable."
	exit 1
fi

if [ ! -f "$PYFILE" ]; then
	echo "Error: Python file '$PYFILE' not found."
	exit 1
fi

python3 "$PYFILE"
